name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: depot-ubuntu-22.04-4,dagger=0.15.1
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: dagger call build
